### PR TITLE
chore: user profile page

### PR DESCRIPTION
**Pull request by EugeneDevv**

### CODE REVIEW

**Comment by EugeneDevv** [comment]
Screenshot_20211001-105816

**Comment by EugeneDevv** [comment]
Screenshot_20211001-105826

**Comment by EugeneDevv** [comment]
Screenshot_20211001-172126

**Comment by EugeneDevv** [comment]
Screenshot_20211001-174347

**Comment by EugeneDevv** [comment]
Screenshot_20211001-174147

**Review by abiudrn — APPROVED** [review]

**Pull request merged**
